
package airlinereservation;

import java.awt.*;

/**
 * This class represents the GUI interface for Airline Reservation.
 * @see Airline Reservation
 * @author Samreth, Ritty
 * @author Reginato, Adolfo
 * @author Ben, Sethey 
 */

public class AirlineReservationForm extends javax.swing.JFrame {
    /**
     * Creates new form AirlineReservationForm
     */
 	int sectionSelect;
        int firstClass;
        int economyClass;
 	boolean seats[];
 	boolean question = false;
        Image[ ] seatImages; //variable for photo array
    
    public AirlineReservationForm() {
        initComponents();
        firstClass = 0;
	economyClass = 5;
	seats = new boolean[10];
	for(int index = 0;index < seats.length;index++)
	seats[index] = false;
        this.getContentPane().setBackground( new Color (2,44,82));
        noButton.setEnabled(false);
        yesButton.setEnabled(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        horizontalBar = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        verticalBar = new javax.swing.JSeparator();
        seat4 = new javax.swing.JLabel();
        seat1 = new javax.swing.JLabel();
        seat3 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        seat5 = new javax.swing.JLabel();
        seat6 = new javax.swing.JLabel();
        seat7 = new javax.swing.JLabel();
        seat8 = new javax.swing.JLabel();
        seat9 = new javax.swing.JLabel();
        seat10 = new javax.swing.JLabel();
        seatPlan = new javax.swing.JLabel();
        verticalBar2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 450));
        getContentPane().setLayout(null);

        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });
        getContentPane().add(userInput);
        userInput.setBounds(10, 140, 40, 20);

        classLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classLabel.setForeground(new java.awt.Color(255, 255, 255));
        classLabel.setText("Enter 1 for First Class or 2 for Economy Class");
        getContentPane().add(classLabel);
        classLabel.setBounds(60, 140, 320, 20);

        yesButton.setText("YES");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yesButton);
        yesButton.setBounds(10, 230, 70, 23);

        noButton.setText("NO");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });
        getContentPane().add(noButton);
        noButton.setBounds(100, 230, 70, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 360, 30);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/airplane.jpg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(0, 0, 140, 120);
        getContentPane().add(horizontalBar);
        horizontalBar.setBounds(0, 120, 650, 50);

        title.setFont(new java.awt.Font("Impact", 2, 50)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("RSA Airlines");
        getContentPane().add(title);
        title.setBounds(180, 10, 270, 90);

        slogan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setText("What's your destination?");
        getContentPane().add(slogan);
        slogan.setBounds(350, 80, 240, 40);

        verticalBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(verticalBar);
        verticalBar.setBounds(140, 0, 50, 120);

        seat4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat4.setText("#4");
        getContentPane().add(seat4);
        seat4.setBounds(470, 230, 40, 20);

        seat1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat1.setText("#1");
        getContentPane().add(seat1);
        seat1.setBounds(510, 170, 40, 14);

        seat3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat3.setText("#3");
        getContentPane().add(seat3);
        seat3.setBounds(540, 190, 60, 30);

        seat2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat2.setText("#2");
        getContentPane().add(seat2);
        seat2.setBounds(480, 194, 40, 20);

        seat5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seat5.setText("#5");
        getContentPane().add(seat5);
        seat5.setBounds(530, 220, 70, 40);

        seat6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat6.setText("#6");
        getContentPane().add(seat6);
        seat6.setBounds(474, 330, 50, 20);

        seat7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat7.setText("#7");
        getContentPane().add(seat7);
        seat7.setBounds(554, 330, 40, 20);

        seat8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seat8.setText("#8");
        getContentPane().add(seat8);
        seat8.setBounds(460, 350, 40, 30);

        seat9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seat9.setText("#9");
        getContentPane().add(seat9);
        seat9.setBounds(544, 354, 40, 20);

        seat10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seat10.setText("#10");
        getContentPane().add(seat10);
        seat10.setBounds(490, 380, 50, 20);

        seatPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlinereservation/planeLayout.gif"))); // NOI18N
        getContentPane().add(seatPlan);
        seatPlan.setBounds(410, 120, 190, 300);

        verticalBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(verticalBar2);
        verticalBar2.setBounds(400, 120, 40, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
        sectionSelect = Integer.parseInt(userInput.getText());
        String output = "";
	question = false;
        noButton.setEnabled(false);
        yesButton.setEnabled(false);
                
        if (sectionSelect == 1)
            {
                if (firstClass<5)
                    {
                        seats[firstClass]=true;
                        output = "First Class. Seat #"+ ++firstClass;
                    }
                else if (firstClass>=5 && economyClass<10)
                    {
                        output = "First Class is full. Economy Class?";
                        question = true;
                        noButton.setEnabled(true);
                        yesButton.setEnabled(true);
                        userInput.setText("");
                        userInput.requestFocus();
                    }
                else {
                    output = "Flight is full. Try next flight.";
                    userInput.setText("");
                }
            }	
                
        else if (sectionSelect == 2)
            {
                if(economyClass < 10)
                    {
                        seats[economyClass] = true;
                        output = "Economy Class. Seat #"+ ++economyClass;
                    }
		else if (economyClass == 10 && firstClass < 5)
                    {
                        output = "Economy class is full. First Class?";
                        question = true;
                        noButton.setEnabled(true);
                        yesButton.setEnabled(true);
                        userInput.setText("");
                        userInput.requestFocus();
                    }
		else {
                    output = "Flight is full. Try next flight.";
                    userInput.setText("");
                }
            }
        else 
            output = "Invalid input.";
            showMessage(output);
    }//GEN-LAST:event_userInputActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
        noButton.setEnabled(false);
        yesButton.setEnabled(false);
        
        if (question)
            {
                if (sectionSelect == 1)
                    {
                        seats[economyClass] = true;
                        showMessage("Economy Class.Seat #"+ ++economyClass);
                     }
                else
                    {
                        seats[firstClass] = true;
                        showMessage("First Class. Seat #"+ ++firstClass);
                    }
                question = false;
                }
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
        noButton.setEnabled(false);
        yesButton.setEnabled(false);
         if(question)
              showMessage("Next flight leaves in 3 hours.");
              question = false;        
    }//GEN-LAST:event_noButtonActionPerformed

    public void arrayPhoto() {
        seatImages = new Image[10];
        seatImages[0] = getImage( getDocumentBase(), "redSeat.gif");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineReservationForm().setVisible(true);
            }
        });
    }
    
    public void showMessage(String message)
    {
        jLabel3.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classLabel;
    private javax.swing.JSeparator horizontalBar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat10;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel seat3;
    private javax.swing.JLabel seat4;
    private javax.swing.JLabel seat5;
    private javax.swing.JLabel seat6;
    private javax.swing.JLabel seat7;
    private javax.swing.JLabel seat8;
    private javax.swing.JLabel seat9;
    private javax.swing.JLabel seatPlan;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userInput;
    private javax.swing.JSeparator verticalBar;
    private javax.swing.JSeparator verticalBar2;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
